- stage: DeployToBuildEnv
  jobs:
  - deployment: Deploy
    displayName: 'Deploy to Build Environment'
    environment: 'Build'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo 'Deploying...'
