# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  condition: 
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo Building the application
      displayName: 'Build'

- stage: Dev
  jobs:
  - job: DevJob
    steps:
    - script: echo Deploying to Dev environment
      displayName: 'Deploy to Dev'

- stage: Test
  jobs:
  - job: TestJob
    steps:
    - script: echo Running tests in Test environment
      displayName: 'Run tests'

- stage: SIT
  jobs:
  - job: SITJob
    steps:
    - script: echo Deploying to SIT environment
      displayName: 'Deploy to SIT'

- stage: Preprod
  jobs:
  - job: PreprodJob
    steps:
    - script: echo Deploying to Preprod environment
      displayName: 'Deploy to Preprod'

- stage: Prod
  jobs:
  - job: ProdJob
    steps:
    - script: echo Deploying to Prod environment
      displayName: 'Deploy to Prod'

