trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: echo 'Building...'

- stage: DeployToBuildEnv
  jobs:
  - deployment: Deploy
    displayName: 'Deploy to Build Environment'
    environment: 'Build'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo 'Deploying...'

- stage: Test
  jobs:
  - job: Test
    steps:
    - script: echo 'Testing...'

# Define more stages and jobs as needed...

